name: D2 and D3 tests

on:
  push:
    branches:
      - "**"

jobs:
  basic_test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v5

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instala Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r Secure_Symmetric_Encryption_Module/tests/requirements.txt

      - name: Pruebas D2 (Secure Symmetric Encryption)
        run: |
          pytest Secure_Symmetric_Encryption_Module/tests/

      - name: Pruebas D3 (Hybrid Encryption)
        run: |
          pytest Secure_Hybrid_Encryption_Module/tests/
